### ISSUE TITLE
'tomlq' binary not installed unless 'color' feature is enabled

### ISSUE THREAD

**Issue by kpfleming** [cryptaliagy/tomlq#11]
https://github.com/cryptaliagy/tomlq/blob/232ed2e856dde2c742bb61ee8c99789a655ae124/Cargo.toml#L46

I've just installed this package as a dependency in a project which does not request the `color` feature, and the `tomlq` binary was not present. I've already changed the project to use `tq` instead, but the README file may need to be updated to reflect that `tomlq` won't be present unless that feature is enabled during the installation.

**Comment by cryptaliagy** [comment]
Thank you for the contribution- I'll update the code to allow `color` to be truly optional so `tomlq` can still be used even without it
