### ISSUE TITLE
tomlq package on crates.io doesn't include Cargo.lock file

### ISSUE THREAD

**Issue by mykmelez** [cryptaliagy/tomlq#2]
The tomlq package on crates.io doesn't appear to include the Cargo.lock file in this repository, so it isn't possible to use the `--locked` flag to `cargo install` to make Cargo build the tool with the particular versions of the dependencies specified in that file. Per https://doc.rust-lang.org/cargo/commands/cargo-install.html:

> The --locked flag can be used to force Cargo to use the packaged Cargo.lock file if it is available. This may be useful for ensuring reproducible builds, to use the exact same set of dependencies that were available when the package was published. It may also be useful if a newer version of a dependency is published that no longer builds on your system, or has other problems.

This came up for me recently when I tried to build an old release branch of some software that uses tomlq and is pinned to Rust 1.43.1. tomlq depends on clap, and the Cargo.lock file in this repo specifies clap version 2.26.0, but `cargo install tomlq` tries to use clap-2.33.3, which isn't compatible with Rust 1.43.1.

If I was able to `cargo install --locked tomlq`, then I'd be able to build it with Rust 1.43.1 when building the old release.

I *think* this just requires publishing a new version of this crate with a modern version of Cargo, as https://doc.rust-lang.org/cargo/commands/cargo-install.html notes:

> Cargo did not start publishing Cargo.lock files until version 1.37, which means packages published with prior versions will not have a Cargo.lock file available.

**Comment by cryptaliagy** [comment]
This is now resolved and should be publishing correctly!
